
INSERT INTO PARKING_LOT(NAME, ADDRESS)  VALUES ('P1', 'Mumbai');
INSERT INTO PARKING_LOT(NAME, ADDRESS)  VALUES ('P2', 'Pune');
INSERT INTO PARKING_LOT(NAME, ADDRESS)  VALUES ('P3', 'Bangalore');

INSERT INTO PARKING_UNIT(VEHICLE_TYPE, TOTAL, P_LOT_ID) VALUES ('Bike', 10, '1');
INSERT INTO PARKING_UNIT(VEHICLE_TYPE, TOTAL, P_LOT_ID) VALUES ('Car', 20, '1');
INSERT INTO PARKING_UNIT(VEHICLE_TYPE, TOTAL, P_LOT_ID) VALUES ('Bike', 5, '2');
INSERT INTO PARKING_UNIT(VEHICLE_TYPE, TOTAL, P_LOT_ID) VALUES ('Car', 15, '2');
INSERT INTO PARKING_UNIT(VEHICLE_TYPE, TOTAL, P_LOT_ID) VALUES ('Bike', 20, '3');
INSERT INTO PARKING_UNIT(VEHICLE_TYPE, TOTAL, P_LOT_ID) VALUES ('Car', 30, '3');

INSERT INTO PARKING_UNIT_RATE(RATE, FREQUENCY, P_UNIT_ID) VALUES (20, 1, '1');
INSERT INTO PARKING_UNIT_RATE(RATE, FREQUENCY, P_UNIT_ID) VALUES (40, 1, '2');
INSERT INTO PARKING_UNIT_RATE(RATE, FREQUENCY, P_UNIT_ID) VALUES (20, 1, '3');
INSERT INTO PARKING_UNIT_RATE(RATE, FREQUENCY, P_UNIT_ID) VALUES (50, 1, '4');
INSERT INTO PARKING_UNIT_RATE(RATE, FREQUENCY, P_UNIT_ID) VALUES (10, 1, '5');
INSERT INTO PARKING_UNIT_RATE(RATE, FREQUENCY, P_UNIT_ID) VALUES (30, 1, '6');

INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('A', 'MUMBAI');
INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('B', 'PUNE');
INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('C', 'MUMBAI');
INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('D', 'MUMBAI');
INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('E', 'BANGALORE');
INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('F', 'MUMBAI');
INSERT INTO OWNER(OWNER_NAME, OWNER_ADDRESS) VALUES ('G', 'PUNE');

INSERT INTO VEHICLE(VEHICLE_NUMBER, OWNER_ID, TYPE) VALUES ('1', 1, 'Bike');
INSERT INTO VEHICLE(VEHICLE_NUMBER, OWNER_ID, TYPE) VALUES ('2', 2, 'Car');
INSERT INTO VEHICLE(VEHICLE_NUMBER, OWNER_ID, TYPE) VALUES ('3', 3, 'Bike');
INSERT INTO VEHICLE(VEHICLE_NUMBER, OWNER_ID, TYPE) VALUES ('4', 4, 'Car');
INSERT INTO VEHICLE(VEHICLE_NUMBER, OWNER_ID, TYPE) VALUES ('5', 5, 'Car');
INSERT INTO VEHICLE(VEHICLE_NUMBER, OWNER_ID, TYPE) VALUES ('6', 6, 'Bike');
 
