DROP TABLE IF EXISTS TEMP;
 
CREATE TABLE PARKING_LOT (
  p_lot_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL
);

CREATE TABLE PARKING_UNIT (
  p_unit_id INT AUTO_INCREMENT PRIMARY KEY,
  vehicle_type VARCHAR(10) NOT NULL,
  total INT NOT NULL,
  current INT,
  p_lot_id INT,
  foreign key (p_lot_id) references PARKING_LOT(p_lot_id)
);

CREATE TABLE OWNER (
  OWNER_ID INT AUTO_INCREMENT ,
  OWNER_NAME VARCHAR(250) NOT NULL,
  OWNER_ADDRESS VARCHAR(250) NOT NULL
);

CREATE TABLE VEHICLE (
  VEHICLE_ID INT AUTO_INCREMENT ,
  VEHICLE_NUMBER VARCHAR(20) PRIMARY KEY,
  OWNER_ID INT,
  TYPE VARCHAR(10) NOT NULL,
  foreign key (OWNER_ID) references OWNER(OWNER_ID)
);

CREATE TABLE PARKING_UNIT_RATE (
  P_RATE_ID INT AUTO_INCREMENT PRIMARY KEY,
  RATE INT NOT NULL,
  FREQUENCY INT NOT NULL,
  P_UNIT_ID INT,
  foreign key (P_UNIT_ID) references PARKING_UNIT(P_UNIT_ID)
);

CREATE TABLE VEHICLE_PARKING_MAPPING (
	vehicle_parking_id INT AUTO_INCREMENT PRIMARY KEY,
	START_TIME DATE NOT NULL,
	END_TIME DATE,
	AMOUNT INT,
	P_UNIT_ID INT,
	VEHICLE_NUMBER VARCHAR(20),
  	foreign key (P_UNIT_ID) references PARKING_UNIT(P_UNIT_ID),
  	foreign key (VEHICLE_NUMBER) references VEHICLE(VEHICLE_NUMBER)
);